services:
  backend:
    container_name: backend
    build:
      context: .  # Assumes Dockerfile is in the backend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Backend on port 3000
    env_file:
      - .env  # Assumes .env is in the backend directory
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - shared-network

networks:
  shared-network:
    external: true