version: '3.8'

services:
  app:
    container_name: ecommerce-backend
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env  # Automatically loads environment variables
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always  # Restarts if it crashes
    networks:
      - shared-network

networks:
  shared-network:
    external: true