version: '3.8'
services:
  express-app:
    build:
      context: ./EcommerceBackend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FLASK_URL=http://flask-app:5000
      - MONGO_URL=mongodb://root:example@103.155.161.94:27017/recommendation_system?authSource=admin  # ✅ Updated
      - KAFKA_URL=kafka-service:9092
    depends_on:
      - flask-app
      - kafka-service  # ✅ Removed mongodb-service
    env_file:
      - ./EcommerceBackend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://express-app:3000/health"]
      interval: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  flask-app:
    build:
      context: ./Ai_recommendation
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://flask-app:5000/health"]
      interval: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  zookeeper-service:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    logging:
      driver: "none"

  kafka-service:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-service
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      retries: 3
    logging:
      driver: "none"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka-service
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka-service:9092
      KAFKA_TOPICS: '*'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 3
    logging:
      driver: "none"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      - express-app
      - flask-app
    logging:
      driver: "none"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    logging:
      driver: "none"

# ✅ Removed mongodb-service and its volume
